### PR TITLE
Added script to check for and install `xdo`. Updated README file.

### PR DESCRIPTION
**Pull request by tzekid**
Thought of making it easier for noobs to use this lib, so I wrote a simple script to run before `nimble install`.

Should the script be completely separate of the `nimble install` process, or is this behaviour OK? What do you think @juancarlospaco ?

### CODE REVIEW

**Comment by juancarlospaco** [comment]
Try to use at least short but descriptive commit messages.

I prefer everyone installs nim-xdo using nimble, not manually.

Should be cool to add to the install instructions something like:

> First check if your Distros package manager dont have a package for XDo

Some Distros might have, Arch have, probably others too.

is definitely an improvement, but ideally we should use [NimScript](https://nim-lang.org/docs/nims.html) instead of Bash.

I dont know if running it automatically on install in a mandatory way,
we can lose more users if Bash fails for some reason,
maybe we can include it and let the user run it manually.

:thinking:

**Comment by tzekid** [comment]
> but ideally we should use nims instead of bash

My biggest trifle with nims right now is that you cannot get user input (afaik), and I'd like the script to be somewhat interactive ... on the other hand one could break the functionality into 2 scripts: an interface, in bash, and the standalone logic in nims.

> we can lose more users if Bash fails for some reason

Good point - make it optional and warn users more concisely (in the README) that they need `xdo` in the first place for the app to work at all.

**Comment by tzekid** [comment]
How about detecting inside the nim-xdo lib itself if the user has xdo installed ? Right now it simply fails (and not graciously at all) if one tries to use the lib w/o xdo installed.

**Comment by juancarlospaco** [comment]
I prefer to keep the installations as automated as possible.

I think the best should be to detect the existence of XDo on Nim, being Nim or NimScript.

Theres [a constant of XDo version on the top of the module](https://github.com/juancarlospaco/nim-xdo/blob/master/src/xdo.nim#L10), 
maybe use a `try except` there, if it fails print a red warning with `styledEcho`.

**Pull request merged**
